/**
 * @file    CommunicationModuleToolbox
 * @author  menagec
 * @date    16 avril 2015
 * @brief   brief
 * @details details
 */

#ifndef COMMUNICATIONMODULETOOLBOX_H_
#define COMMUNICATIONMODULETOOLBOX_H_

//System includes
//Libraries
//Application includes
#include "LoggingModule/LoggerManager.h"

namespace CommunicationModule
{
    #define COMMUNICATION_MODULE_NAME LoggingModule::LoggerManager::eLogModuleType::LOG_COMMUNICATION_MODULE

    #define COMMUNICATIONMODULE_LOG_INFORMATION_OBJECT_METHOD    LOG_INFORMATION_OBJECT_METHOD(COMMUNICATION_MODULE_NAME)
    #define COMMUNICATIONMODULE_LOG_INFORMATION_MESSAGE(msg)     LOG_INFORMATION_MESSAGE(COMMUNICATION_MODULE_NAME,msg)
    #define COMMUNICATIONMODULE_LOG_DEBUG_MESSAGE(msg)           LOG_DEBUG_MESSAGE(COMMUNICATION_MODULE_NAME,msg)
    #define COMMUNICATIONMODULE_LOG_WARN_MESSAGE(msg)            LOG_WARN_MESSAGE(COMMUNICATION_MODULE_NAME,msg)
    #define COMMUNICATIONMODULE_LOG_ERROR_MESSAGE(msg)           LOG_ERROR_MESSAGE(COMMUNICATION_MODULE_NAME,msg)
    #define COMMUNICATIONMODULE_LOG_FATAL_MESSAGE(msg)           LOG_FATAL_MESSAGE(COMMUNICATION_MODULE_NAME,msg)
}

#endif /* COMMUNICATIONMODULETOOLBOX_H_ */
